# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# update the ignore_unmapped list if you want to exclude certain appliations from the unmapped control
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master
  1: deej.unmapped
  2: discord.exe
  3: brave.exe

#ignore_unmapped:
  #- rambox.exe

# Slider name must be separated by | and less than 20 characters each
slider_names:
  0: MASTER
  1: ALL
  2: DISCORD
  3: BROWSER

# Optional: set maximum volume limits for each slider (values are percentages from 1-100)
# When a slider is at 100%, the volume will be set to the specified percentage
slider_max_volume:
  0: 100  # Master volume is always 100%
  1: 50   # All unmapped apps limited to 40%
  2: 50   # Discord volume limited to 40%
  3: 30   # Browser volume limited to 20%

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM5
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default

